/* gen-abi.c -- emit a Lisp file of exact PipeWire/SPA ABI constants.
 *
 * Compile & run (see src/gen-abi.sh) to regenerate src/pw-abi.lisp. This keeps
 * the pure-Lisp CFFI bindings honest against the installed headers instead of
 * hard-coding struct offsets and enum values.
 *
 * We can't call SPA's static-inline POD builders from Lisp, so we hand-assemble
 * PODs; this file gives us every magic number needed to do that correctly.
 */
#include <stdio.h>
#include <stddef.h>
#include <pipewire/pipewire.h>
#include <spa/param/format.h>
#include <spa/param/format-utils.h>
#include <spa/param/video/format-utils.h>
#include <spa/param/video/raw.h>
#include <spa/param/param.h>
#include <spa/param/buffers.h>
#include <spa/buffer/meta.h>
#include <spa/buffer/buffer.h>
#include <spa/pod/pod.h>
#include <spa/utils/type.h>

#define OFF(sym, s, f)   printf("(defconstant +%s+ %zu)\n", sym, offsetof(struct s, f))
#define SZ(sym, s)       printf("(defconstant +%s+ %zu)\n", sym, sizeof(struct s))
#define C(sym, v)        printf("(defconstant +%s+ %ld)\n", sym, (long)(v))
#define CU(sym, v)       printf("(defconstant +%s+ #x%lx)\n", sym, (unsigned long)(v))

int main(void)
{
    printf(";;;; pw-abi.lisp -- GENERATED by src/gen-abi.c. Do not edit by hand.\n");
    printf("(in-package #:green-screen/pipewire)\n\n");

    printf(";;; --- struct sizes & offsets ---\n");
    SZ("sz/pw-buffer", pw_buffer);
    OFF("off/pw-buffer/buffer", pw_buffer, buffer);

    SZ("sz/spa-buffer", spa_buffer);
    OFF("off/spa-buffer/n-metas", spa_buffer, n_metas);
    OFF("off/spa-buffer/n-datas", spa_buffer, n_datas);
    OFF("off/spa-buffer/metas", spa_buffer, metas);
    OFF("off/spa-buffer/datas", spa_buffer, datas);

    SZ("sz/spa-data", spa_data);
    OFF("off/spa-data/type", spa_data, type);
    OFF("off/spa-data/flags", spa_data, flags);
    OFF("off/spa-data/fd", spa_data, fd);
    OFF("off/spa-data/mapoffset", spa_data, mapoffset);
    OFF("off/spa-data/maxsize", spa_data, maxsize);
    OFF("off/spa-data/chunk", spa_data, chunk);
    OFF("off/spa-data/data", spa_data, data);

    SZ("sz/spa-chunk", spa_chunk);
    OFF("off/spa-chunk/offset", spa_chunk, offset);
    OFF("off/spa-chunk/size", spa_chunk, size);
    OFF("off/spa-chunk/stride", spa_chunk, stride);

    SZ("sz/spa-meta", spa_meta);
    OFF("off/spa-meta/type", spa_meta, type);
    OFF("off/spa-meta/size", spa_meta, size);
    OFF("off/spa-meta/data", spa_meta, data);

    SZ("sz/spa-meta-cursor", spa_meta_cursor);
    OFF("off/spa-meta-cursor/id", spa_meta_cursor, id);
    OFF("off/spa-meta-cursor/flags", spa_meta_cursor, flags);
    OFF("off/spa-meta-cursor/position", spa_meta_cursor, position);
    OFF("off/spa-meta-cursor/hotspot", spa_meta_cursor, hotspot);
    OFF("off/spa-meta-cursor/bitmap-offset", spa_meta_cursor, bitmap_offset);
    OFF("off/spa-point/x", spa_point, x);
    OFF("off/spa-point/y", spa_point, y);

    SZ("sz/pw-stream-events", pw_stream_events);
    OFF("off/pw-stream-events/version", pw_stream_events, version);
    OFF("off/pw-stream-events/destroy", pw_stream_events, destroy);
    OFF("off/pw-stream-events/state-changed", pw_stream_events, state_changed);
    OFF("off/pw-stream-events/param-changed", pw_stream_events, param_changed);
    OFF("off/pw-stream-events/add-buffer", pw_stream_events, add_buffer);
    OFF("off/pw-stream-events/remove-buffer", pw_stream_events, remove_buffer);
    OFF("off/pw-stream-events/process", pw_stream_events, process);
    SZ("sz/spa-hook", spa_hook);
    SZ("sz/spa-pod", spa_pod);

    printf("\n;;; --- versions & flags ---\n");
    C("pw-version-stream-events", PW_VERSION_STREAM_EVENTS);
    C("pw-stream-flag-autoconnect", PW_STREAM_FLAG_AUTOCONNECT);
    C("pw-stream-flag-map-buffers", PW_STREAM_FLAG_MAP_BUFFERS);
    C("pw-stream-state-error", PW_STREAM_STATE_ERROR);
    C("pw-stream-state-unconnected", PW_STREAM_STATE_UNCONNECTED);
    C("pw-stream-state-connecting", PW_STREAM_STATE_CONNECTING);
    C("pw-stream-state-paused", PW_STREAM_STATE_PAUSED);
    C("pw-stream-state-streaming", PW_STREAM_STATE_STREAMING);
    C("spa-direction-input", SPA_DIRECTION_INPUT);
    CU("spa-id-invalid", SPA_ID_INVALID);

    printf("\n;;; --- SPA base types (for hand-built PODs) ---\n");
    C("spa-type-none", SPA_TYPE_None);
    C("spa-type-bool", SPA_TYPE_Bool);
    C("spa-type-id", SPA_TYPE_Id);
    C("spa-type-int", SPA_TYPE_Int);
    C("spa-type-long", SPA_TYPE_Long);
    C("spa-type-rectangle", SPA_TYPE_Rectangle);
    C("spa-type-fraction", SPA_TYPE_Fraction);
    C("spa-type-array", SPA_TYPE_Array);
    C("spa-type-struct", SPA_TYPE_Struct);
    C("spa-type-object", SPA_TYPE_Object);
    C("spa-type-choice", SPA_TYPE_Choice);
    C("spa-type-pod", SPA_TYPE_Pod);
    C("spa-type-object-format", SPA_TYPE_OBJECT_Format);
    C("spa-type-object-param-buffers", SPA_TYPE_OBJECT_ParamBuffers);
    C("spa-type-object-param-meta", SPA_TYPE_OBJECT_ParamMeta);

    printf("\n;;; --- choice types ---\n");
    C("spa-choice-none", SPA_CHOICE_None);
    C("spa-choice-range", SPA_CHOICE_Range);
    C("spa-choice-step", SPA_CHOICE_Step);
    C("spa-choice-enum", SPA_CHOICE_Enum);

    printf("\n;;; --- param ids ---\n");
    C("spa-param-enum-format", SPA_PARAM_EnumFormat);
    C("spa-param-format", SPA_PARAM_Format);
    C("spa-param-buffers", SPA_PARAM_Buffers);
    C("spa-param-meta", SPA_PARAM_Meta);

    printf("\n;;; --- format object property keys ---\n");
    C("spa-format-media-type", SPA_FORMAT_mediaType);
    C("spa-format-media-subtype", SPA_FORMAT_mediaSubtype);
    C("spa-format-video-format", SPA_FORMAT_VIDEO_format);
    C("spa-format-video-size", SPA_FORMAT_VIDEO_size);
    C("spa-format-video-framerate", SPA_FORMAT_VIDEO_framerate);
    C("spa-media-type-video", SPA_MEDIA_TYPE_video);
    C("spa-media-subtype-raw", SPA_MEDIA_SUBTYPE_raw);

    printf("\n;;; --- ParamMeta / ParamBuffers keys ---\n");
    C("spa-param-meta-type", SPA_PARAM_META_type);
    C("spa-param-meta-size", SPA_PARAM_META_size);
    C("spa-param-buffers-buffers", SPA_PARAM_BUFFERS_buffers);
    C("spa-param-buffers-blocks", SPA_PARAM_BUFFERS_blocks);
    C("spa-param-buffers-size", SPA_PARAM_BUFFERS_size);
    C("spa-param-buffers-stride", SPA_PARAM_BUFFERS_stride);
    C("spa-param-buffers-datatype", SPA_PARAM_BUFFERS_dataType);

    printf("\n;;; --- video formats (BGRA/RGBA family) ---\n");
    C("spa-video-format-rgb", SPA_VIDEO_FORMAT_RGB);
    C("spa-video-format-rgba", SPA_VIDEO_FORMAT_RGBA);
    C("spa-video-format-rgbx", SPA_VIDEO_FORMAT_RGBx);
    C("spa-video-format-bgra", SPA_VIDEO_FORMAT_BGRA);
    C("spa-video-format-bgrx", SPA_VIDEO_FORMAT_BGRx);
    C("spa-video-format-argb", SPA_VIDEO_FORMAT_ARGB);
    C("spa-video-format-xrgb", SPA_VIDEO_FORMAT_xRGB);

    printf("\n;;; --- meta & data types ---\n");
    C("spa-meta-header", SPA_META_Header);
    C("spa-meta-cursor", SPA_META_Cursor);
    C("spa-meta-bitmap", SPA_META_Bitmap);
    C("spa-data-memptr", SPA_DATA_MemPtr);
    C("spa-data-memfd", SPA_DATA_MemFd);
    C("spa-data-dmabuf", SPA_DATA_DmaBuf);

    return 0;
}
