;;;; SPDX-FileCopyrightText: Copyright (C) 2026 Anthony Green <green@moxielogic.com>
;;;; SPDX-License-Identifier: GPL-3.0-or-later
;;;; pipewire-package.lisp
;;;;
;;;; Bead green-screen-jme: pure-Lisp CFFI bindings to libpipewire-0.3.
;;;;
;;;; Package + foreign-library + raw function bindings only. The ABI constants
;;;; live in pw-abi.lisp (generated by gen-abi.c) and load after this file; the
;;;; capture logic and hand-built SPA PODs live in pipewire.lisp.
;;;;
;;;; We bind only exported libpipewire symbols. SPA's helpers (spa_pod_builder_*,
;;;; the SPA_POD_* macros) are static-inline and NOT callable via FFI, so the
;;;; format-negotiation PODs are assembled byte-by-byte in Lisp instead.

(defpackage #:takesy/pipewire
  (:use #:cl)
  (:nicknames #:tk-pw)
  (:export #:capture-one-frame #:capture-frame-to-png
           #:record-frames #:load-recording
           #:format->gl-source-format))

(in-package #:takesy/pipewire)

(cffi:define-foreign-library libpipewire
  (:unix (:or "libpipewire-0.3.so.0" "libpipewire-0.3.so"))
  (t (:default "libpipewire-0.3")))

(unless (cffi:foreign-library-loaded-p 'libpipewire)
  (cffi:use-foreign-library libpipewire))

;;; ------------------------------------------------------------------
;;; Core library / main loop.

(cffi:defcfun ("pw_init" pw-init) :void
  (argc :pointer) (argv :pointer))

(cffi:defcfun ("pw_deinit" pw-deinit) :void)

(cffi:defcfun ("pw_main_loop_new" pw-main-loop-new) :pointer
  (props :pointer))

(cffi:defcfun ("pw_main_loop_get_loop" pw-main-loop-get-loop) :pointer
  (loop :pointer))

(cffi:defcfun ("pw_main_loop_run" pw-main-loop-run) :int
  (loop :pointer))

(cffi:defcfun ("pw_main_loop_quit" pw-main-loop-quit) :int
  (loop :pointer))

(cffi:defcfun ("pw_main_loop_destroy" pw-main-loop-destroy) :void
  (loop :pointer))

;;; ------------------------------------------------------------------
;;; Context / core (connect via the portal's fd).

(cffi:defcfun ("pw_context_new" pw-context-new) :pointer
  (loop :pointer) (props :pointer) (user-data-size :size))

(cffi:defcfun ("pw_context_connect_fd" pw-context-connect-fd) :pointer
  (context :pointer) (fd :int) (props :pointer) (user-data-size :size))

(cffi:defcfun ("pw_context_destroy" pw-context-destroy) :void
  (context :pointer))

(cffi:defcfun ("pw_core_disconnect" pw-core-disconnect) :int
  (core :pointer))

;;; ------------------------------------------------------------------
;;; Stream.

(cffi:defcfun ("pw_stream_new" pw-stream-new) :pointer
  (core :pointer) (name :string) (props :pointer))

(cffi:defcfun ("pw_stream_add_listener" pw-stream-add-listener) :void
  (stream :pointer) (hook :pointer) (events :pointer) (data :pointer))

(cffi:defcfun ("pw_stream_connect" pw-stream-connect) :int
  (stream :pointer) (direction :int) (target-id :uint32)
  (flags :int) (params :pointer) (n-params :uint32))

(cffi:defcfun ("pw_stream_dequeue_buffer" pw-stream-dequeue-buffer) :pointer
  (stream :pointer))

(cffi:defcfun ("pw_stream_queue_buffer" pw-stream-queue-buffer) :int
  (stream :pointer) (buffer :pointer))

(cffi:defcfun ("pw_stream_update_params" pw-stream-update-params) :int
  (stream :pointer) (params :pointer) (n-params :uint32))

(cffi:defcfun ("pw_stream_get_state" pw-stream-get-state) :int
  (stream :pointer) (error :pointer))

(cffi:defcfun ("pw_stream_disconnect" pw-stream-disconnect) :int
  (stream :pointer))

(cffi:defcfun ("pw_stream_destroy" pw-stream-destroy) :void
  (stream :pointer))

;;; ------------------------------------------------------------------
;;; Properties. pw_properties_new is variadic (ABI-fragile via FFI); the
;;; _string form takes a single "key = value key2 = value2" string.

(cffi:defcfun ("pw_properties_new_string" pw-properties-new-string) :pointer
  (str :string))

(defun make-properties (&rest key-values)
  "Build a pw_properties* from alternating string KEY VALUE args."
  (pw-properties-new-string
   (with-output-to-string (s)
     (loop for (k v) on key-values by #'cddr
           do (format s "~A = ~A " k v)))))
